"""Add description to StoreModel

Revision ID: 822084425a1b
Revises: 5719db6fc871
Create Date: 2025-05-04 00:14:19.544358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822084425a1b'
down_revision = '5719db6fc871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
